name: Deploy PR to GitHub Pages

on:
  pull_request:
    types:
      - opened
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set unique deploy URL
        id: set_url
        run: echo "::set-output name=url::https://pr-${{ github.event.pull_request.number }}.github.io"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Replace with your build output directory
          cname: ${{ steps.set_url.outputs.url }}

